In [39]:
import pandas as pd
import numpy as np

In [40]:
df = pd.read_csv("Desktop/Telco-Customer-Churn.csv")
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [41]:
df.shape

(7043, 21)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [43]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [44]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [45]:
df.columns = df.columns.str.strip().str.lower()

In [46]:
df = df.rename(columns={
    "customerid": "customer_id",
    "seniorcitizen": "senior_citizen",
    "phoneservice": "phone_service",
    "multiplelines": "multiple_lines",
    "internetservice": "internet_service",
    "onlinesecurity": "online_security",
    "onlinebackup": "online_backup",
    "deviceprotection": "device_protection",
    "techsupport": "tech_support",
    "streamingtv": "streaming_tv",
    "streamingmovies": "streaming_movies",
    "paperlessbilling": "paperless_billing",
    "paymentmethod": "payment_method",
    "monthlycharges": "monthly_charges",
    "totalcharges": "total_charges",
    "Churn": "churn"
})

In [47]:
df.columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure', 'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn'],
      dtype='object')

In [48]:
df.dtypes

customer_id           object
gender                object
senior_citizen         int64
partner               object
dependents            object
tenure                 int64
phone_service         object
multiple_lines        object
internet_service      object
online_security       object
online_backup         object
device_protection     object
tech_support          object
streaming_tv          object
streaming_movies      object
contract              object
paperless_billing     object
payment_method        object
monthly_charges      float64
total_charges         object
churn                 object
dtype: object

In [49]:
df["senior_citizen"] = df["senior_citizen"].map({
    0: "No",
    1: "Yes"
})

In [50]:
df["senior_citizen"].value_counts()

senior_citizen
No     5901
Yes    1142
Name: count, dtype: int64

In [51]:
df["total_charges"].unique()

array(['29.85', '1889.5', '108.15', ..., '346.45', '306.6', '6844.5'],
      dtype=object)

In [52]:
df["total_charges"] = df["total_charges"].replace(" ", np.nan)
df['total_charges'] = pd.to_numeric(df['total_charges'], errors='coerce')

In [53]:
df["total_charges"].dtype

dtype('float64')

In [54]:
df.isnull().sum()

customer_id           0
gender                0
senior_citizen        0
partner               0
dependents            0
tenure                0
phone_service         0
multiple_lines        0
internet_service      0
online_security       0
online_backup         0
device_protection     0
tech_support          0
streaming_tv          0
streaming_movies      0
contract              0
paperless_billing     0
payment_method        0
monthly_charges       0
total_charges        11
churn                 0
dtype: int64

In [55]:
df[df["total_charges"].isnull()]

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
488,4472-LVYGI,Female,No,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,No,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,No,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,No,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,No,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,No,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,No,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,No,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,No,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [56]:
df[df["total_charges"].isnull()][
    ["customer_id", "tenure", "monthly_charges", "total_charges", "churn"]
]

     customer_id  tenure  monthly_charges  total_charges churn
488   4472-LVYGI       0            52.55            NaN    No
753   3115-CZMZD       0            20.25            NaN    No
936   5709-LVOEQ       0            80.85            NaN    No
1082  4367-NUYAO       0            25.75            NaN    No
1340  1371-DWPAZ       0            56.05            NaN    No
3331  7644-OMVMY       0            19.85            NaN    No
3826  3213-VVOLG       0            25.35            NaN    No
4380  2520-SGTTA       0            20.00            NaN    No
5218  2923-ARZLG       0            19.70            NaN    No
6670  4075-WKNIU       0            73.35            NaN    No
6754  2775-SEFEE       0            61.90            NaN    No

In [57]:
df.loc[
    df["total_charges"].isnull() & (df["tenure"] == 0),
    "total_charges"
] = 0

In [58]:
df.isnull().sum()

customer_id          0
gender               0
senior_citizen       0
partner              0
dependents           0
tenure               0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_tv         0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
churn                0
dtype: int64

In [59]:
df.duplicated().sum()

0

In [60]:
cat_cols = df.select_dtypes(include="object").columns
cat_cols

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'churn'],
      dtype='object')

In [61]:
for col in cat_cols:
    print(col)
    print(df[col].unique())
    print()

customer_id
['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']

gender
['Female' 'Male']

senior_citizen
['No' 'Yes']

partner
['Yes' 'No']

dependents
['No' 'Yes']

phone_service
['No' 'Yes']

multiple_lines
['No phone service' 'No' 'Yes']

internet_service
['DSL' 'Fiber optic' 'No']

online_security
['No' 'Yes' 'No internet service']

online_backup
['Yes' 'No' 'No internet service']

device_protection
['No' 'Yes' 'No internet service']

tech_support
['No' 'Yes' 'No internet service']

streaming_tv
['No' 'Yes' 'No internet service']

streaming_movies
['No' 'Yes' 'No internet service']

contract
['Month-to-month' 'One year' 'Two year']

paperless_billing
['Yes' 'No']

payment_method
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

churn
['No' 'Yes']

In [62]:
df["tenure_group"] = pd.cut(
    df["tenure"],
    bins=[0, 12, 24, 48, 60, 72],
    labels=["0-12 months", "13-24 months", "25-48 months", "49-60 months", "61-72 months"],
    include_lowest=True
)

In [63]:
tenure_order = {
    "0-12 months": 1,
    "13-24 months": 2,
    "25-48 months": 3,
    "49-60 months": 4,
    "61-72 months": 5
}

df["tenure_group_order"] = df["tenure_group"].astype(str).map(tenure_order)

In [64]:
df["monthly_charge_group"] = pd.cut(
    df["monthly_charges"],
    bins=[0, 35, 70, 100, 120],
    labels=["Low", "Medium", "High", "Very High"]
)

In [65]:
charge_order = {
    "Low": 1,
    "Medium": 2,
    "High": 3,
    "Very High": 4
}

df["monthly_charge_group_order"] = df["monthly_charge_group"].astype(str).map(charge_order)

In [66]:
df[["tenure_group_order", "monthly_charge_group_order"]].isnull().sum()

tenure_group_order            0
monthly_charge_group_order    0
dtype: int64

In [67]:
df[["tenure_group_order", "monthly_charge_group_order"]].head()

   tenure_group_order  monthly_charge_group_order
0                   1                           1
1                   3                           2
2                   1                           2
3                   3                           2
4                   1                           3

In [68]:
df["tenure_group_order"] = df["tenure_group_order"].astype("Int64")
df["monthly_charge_group_order"] = df["monthly_charge_group_order"].astype("Int64")

In [69]:
df["churn_flag"] = df["churn"].map({
    "Yes": 1,
    "No": 0
})

In [70]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = df.select_dtypes(include="object").columns

print("Numerical columns:")
print(numeric_cols)

print("Categorical columns:")
print(categorical_cols)

Numerical columns:
Index(['tenure', 'monthly_charges', 'total_charges', 'tenure_group_order',
       'monthly_charge_group_order', 'churn_flag'],
      dtype='object')
Categorical columns:
Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'churn'],
      dtype='object')

In [71]:
df.info()
df.isnull().sum()
df.duplicated().sum()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 7043 non-null   object
 1   gender                      7043 non-null   object
 2   senior_citizen              7043 non-null   object
 3   partner                     7043 non-null   object
 4   dependents                  7043 non-null   object
 5   tenure                      7043 non-null   int64
 6   phone_service               7043 non-null   object
 7   multiple_lines              7043 non-null   object
 8   internet_service            7043 non-null   object
 9   online_security             7043 non-null   object
 10  online_backup               7043 non-null   object
 11  device_protection           7043 non-null   object
 12  tech_support                7043 non-null   object
 13  streaming_tv                7043 non-null   object
 14  streaming_movies            7043 non-null   object
 15  contract                    7043 non-null   object
 16  paperless_billing           7043 non-null   object
 17  payment_method              7043 non-null   object
 18  monthly_charges             7043 non-null   float64
 19  total_charges               7043 non-null   float64
 20  churn                       7043 non-null   object
 21  tenure_group                7043 non-null   category
 22  tenure_group_order          7043 non-null   Int64
 23  monthly_charge_group        7043 non-null   category
 24  monthly_charge_group_order  7043 non-null   Int64
 25  churn_flag                  7043 non-null   int64
dtypes: Int64(2), category(2), float64(2), int64(2), object(18)
memory usage: 1.3+ MB

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,paperless_billing,payment_method,monthly_charges,total_charges,churn,tenure_group,tenure_group_order,monthly_charge_group,monthly_charge_group_order,churn_flag
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,Yes,Electronic check,29.85,29.85,No,0-12 months,1,Low,1,0
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,No,Mailed check,56.95,1889.50,No,25-48 months,3,Medium,2,0
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,Yes,Mailed check,53.85,108.15,Yes,0-12 months,1,Medium,2,1
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,No,Bank transfer (automatic),42.30,1840.75,No,25-48 months,3,Medium,2,0
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,Yes,Electronic check,70.70,151.65,Yes,0-12 months,1,High,3,1
5,9305-CDSKC,Female,No,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,Electronic check,99.65,820.50,Yes,0-12 months,1,High,3,1
6,1452-KIOVK,Male,No,No,Yes,22,Yes,Yes,Fiber optic,No,...,Yes,Credit card (automatic),89.10,1949.40,No,13-24 months,2,High,3,0
7,6713-OKOMC,Female,No,No,No,10,No,No phone service,DSL,Yes,...,No,Mailed check,29.75,301.90,No,0-12 months,1,Low,1,0
8,7892-POOKP,Female,No,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Electronic check,104.80,3046.05,Yes,25-48 months,3,Very High,4,1
9,6388-TABGU,Male,No,No,Yes,62,Yes,No,DSL,Yes,...,No,Bank transfer (automatic),56.15,3487.95,No,61-72 months,5,Medium,2,0

In [72]:
df.shape

(7043, 26)

In [73]:
df.to_csv("Desktop/cleaned_telco_churn.csv", index=False)

In [74]:
print(len(df.columns))
print(df.columns.tolist())

26
['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents', 'tenure', 'phone_service', 'multiple_lines', 'internet_service', 'online_security', 'online_backup', 'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing', 'payment_method', 'monthly_charges', 'total_charges', 'churn', 'tenure_group', 'tenure_group_order', 'monthly_charge_group', 'monthly_charge_group_order', 'churn_flag']

In [75]:
import os

print(os.path.abspath("Desktop/cleaned_telco_churn.csv"))
print(os.path.exists("Desktop/cleaned_telco_churn.csv"))

/Users/poonampandey/Desktop/cleaned_telco_churn.csv
True